name: Merge Main to Release

on:
  push:
    branches:
      - main
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Create Release Branch if not exists and Merge Main to Release
      run: |
        git fetch --prune --unshallow
        git checkout release || git checkout -b release
        git push origin release
        git fetch origin
        git checkout release
        git merge origin/main --no-edit
        git push origin release
